const dataTeam = [
  {
    id: '1',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Oleksandr Pidvysotskyi',
    role: 'Team Lead - Beckend',
    linkGit: 'https://github.com/Pidvysotskyi',
    linkedin: 'https://www.linkedin.com',
  },
  {
    id: '2',
    imgUrl: require('../../images/team/5_Veronika_Savluk.jpeg'),
    name: 'Veronika Savluk',
    role: 'Team Lead - Frontend',
    linkGit: 'https://github.com/VeronikaSavluk',
    linkedin: 'https://www.linkedin.com/in/veronikasavluk',
  },
  {
    id: '3',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Bogdan Karpenko',
    role: 'Team Lead - QA',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '4',
    imgUrl: require('../../images/team/4_Nataliia_Pogreniak.jpg'),
    name: 'Nataliia Pogrebniak',
    role: 'Scrum master',
    linkGit: 'https://github.com/PNataliya',
    linkedin: 'https://www.linkedin.com/in/nataliya-pogrebnyak-80655b73',
  },
  {
    id: '5',
    imgUrl: require('../../images/team/7_Nikita_Rohovoi.jpeg'),
    name: 'Nikita Rohovoi',
    role: 'Frontend developer',
    linkGit: 'https://github.com/NRohovoi',
    linkedin: 'https://www.linkedin.com/in/nikita-rohovoi-6a4aa9241',
  },
  {
    id: '6',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Victoria Myzyniuk',
    role: 'Frontend developer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '7',
    imgUrl: require('../../images/team/9_Stas_Korobchenko.jpeg'),
    name: 'Stanislav Korobchenko',
    role: 'Frontend developer',
    linkGit: 'https://github.com/Stasxxx',
    linkedin: 'https://www.linkedin.com/in/stanislav-korobchenko-b090b9126',
  },
  {
    id: '8',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Andrii Pidlubnyi',
    role: 'Frontend developer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '9',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Viktor Hrimli',
    role: 'Frontend developer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '10',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Andrii Kapustnikov',
    role: 'Frontend developer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '11',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Artem Raskhodchikov',
    role: 'Backend developer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
  {
    id: '12',
    imgUrl: require('../../images/team/plug.png'),
    name: 'Kirill Zerkal',
    role: 'QA engineer',
    linkGit: 'https://github.com',
    linkedin: 'https://www.linkedin.com/',
  },
];

export default dataTeam;
